{
 "title": "VocaBoost",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Enter App",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "vocaboost_enter_app_event_count_gauge"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 10, "x": 14, "y": 0 },
   "targets": [
    { "expr": "node_cpu_seconds_total" }
   ]
  },
  {
   "title": "Login",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "vocaboost_login_event_count_gauge"
    }
   ]
  },
  {
   "title": "Logout",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 6 },
   "targets": [
    {
     "expr": "vocaboost_logout_event_count_gauge"
    }
   ]
  },
  {
   "title": "Enter Study Screen",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "vocaboost_enter_study_screen_event_count_gauge"
    }
   ]
  },
  {
   "title": "Leave Study Screen",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 12 },
   "targets": [
    {
     "expr": "vocaboost_leave_study_screen_event_count_gauge"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "description": "memory used in GB",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 12 },
   "targets": [
    {
     "expr": "node_memory_active_bytes / 1000000000"
    }
   ]
  }
 ]
}